### ISSUE TITLE
XMR Nanopool

### ISSUE THREAD

**Issue by tpoxa** [notgiven688/webminerpool#19]
I entered 4AKM8ivKgebhjzDhdv1sHC6PQRe6CFwpHAnc2SUtRgX31PLHMNz8pNjAmfbRGFhvJgBaBCmzFZAPcPrvVtbu7QVUNqn9zqW

here https://webminerpool.com/
Making 30h/s for half an hour but statistics still empty.
Usually I saw at-lest active workers.. 
https://xmr.nanopool.org/account/4AKM8ivKgebhjzDhdv1sHC6PQRe6CFwpHAnc2SUtRgX31PLHMNz8pNjAmfbRGFhvJgBaBCmzFZAPcPrvVtbu7QVUNqn9zqW

**Comment by notgiven688** [comment]
I think the difficulty of nanopool is quite high. It takes some time to find a job using a webminer. I will try to mine to your account using

https://webminerpool.com?address=4AKM8ivKgebhjzDhdv1sHC6PQRe6CFwpHAnc2SUtRgX31PLHMNz8pNjAmfbRGFhvJgBaBCmzFZAPcPrvVtbu7QVUNqn9zqW&pool=xmr.nanopool.org&password=test

and report back in 10min :)

**Comment by notgiven688** [comment]
Yes. The problem is the very high static difficulty which is suited for miners with approx. 5kH/s. Statistically it should be not a problem, since you find valid shares less often but they are of higher value.

 There are much more diff. friendly pools out there. I recommend moneroocean.stream . Nanopool is about the worst you can chose with a single miner.

**Comment by tpoxa** [comment]
@notgiven688 thank you
