### ISSUE TITLE
Example server for testing

### ISSUE THREAD

**Issue by buchticka666** [notgiven688/webminerpool#41]
Since the example server is taken down, is there any other option to try this miner without running own server? 

Thanks!

**Comment by blonboll** [comment]
I am using this server try it: 
server = "ws://84.42.214.170:8181";

It is working. I have mined already about 0.5XMR...

**Comment by paul0921** [comment]
Have you tried https://minexmr.stream ? Its specifically made for higher loads.

**Comment by PiTi2k5** [comment]
@buchticka666 You can join my crypto community with constant 50000+ active miners/users since nov17 try out crypto-webminer.com for direct mining & integration for websites/blogs with custom pool support and more additional features | core based on webminerpool. There are 6 High End Servers for max performance/load balancing and stability. Or build your own favorite custom mining UI https://github.com/PiTi2k5/Crypto-Webminer.

@paul0921 i hope you support this OS project and send a donation to notgiven688 ;)

**Comment by paul0921** [comment]
@PiTi2k5 Yeah he gets as much of the 5% share that I don't need for AWS payment.
