### ISSUE TITLE
About Cryptonight V2 

### ISSUE THREAD

**Issue by focaeppe** [notgiven688/webminerpool#75]
I'v tested today and i confirm that is slower then the V1
Is there anyone who has tried it before?

**Comment by notgiven688** [comment]
Did you check the cv_v2 branch? Did you compile it yourself? The current cn_v2 branch is slower for v0 and v1 because of some compiler troubles which I already fixed - will update the branch soon. The cn_v2 version is slower because of the additional SQRT and 64bit DIVISION operations. Not much we can do about that - I think.

**Comment by focaeppe** [comment]
Yes compiled and tested on killallasics, i get almost 15% slower :(

**Comment by notgiven688** [comment]
It is expected that cnv2 runs slower, also with other miner programs. The problem is that especially code without cpu intrinsics suffer.

**Comment by notgiven688** [comment]
@focaeppe 
Probably we can cast here to double and do a floating point division which should be faster.
https://github.com/notgiven688/webminerpool/blob/66f1379dbabd3a44483704e7ba3fa1deaf587a35/hash_cn/webassembly/cryptonight.c#L98 

I will test it later.

**Comment by focaeppe** [comment]
@notgiven688 
I really hope it will work ,that will really help
and thanks for your effort

**Comment by notgiven688** [comment]
`const uint64_t aa = (uint64_t)((double)dividend / (double)divisor); `

Indeed speeds up the calculations around 1-2% but fails some corner cases..
