### ISSUE TITLE
No effect on most browsers

### ISSUE THREAD

**Issue by aa224488** [notgiven688/webminerpool#78]
The browser on the mobile phone has no effect and the Baidu browser on the computer side has no effect. What is the reason?

**Comment by aa224488** [comment]
> Safari：永远不会工作
> 勇敢：永远不会工作（但很好......很多东西都不能用于勇敢）
> Chrome：有时可以工作，但是在接受任何哈希之前你必须等待10分钟和一半的击球。

Hello, I have more mobile phone users, want to dig on the phone, but no effect on the phone, some browsers on the computer side have no effect.

**Comment by VidYen** [comment]
I am not 100% sure, but you are simply testing this with just cell phones, you may want to include a few desktop or laptop computers. I have not done a scientific study, but it seems once your server is more active the easier for weaker devices to get hashes (from my experience using Monero Ocean). Of course, I have not tested this theory but it just seems when I tested my Chrome it didn't take 10 minutes yesterday on my iPhone.

Some other things to consider... The phone browser must support Javascript for it to work. If it for some reasons uses some hybrid or water down version on the browser (I am not sure about Baidu browser) it may not work. For example, if I try this on an Xbox 360 browser (I was curious) it won't load at all because that browser has JS support, but not real support so it loads, but does not actually run.

If you are lucky enough to have a Coinhive account (before they started charging) you can see if that work sat all. Coinhive won't load on my XBox 360 browser either.

Also... And this might be something with mainland china... Are you using MoneroOcean for your pool? If so, does any device work? There are some issues with VPN and then I noticed on Reddit.

See if it works with a regular laptop or desktop and if it does, see if it works on a tablet with same OS but better hardware. If it doesn't than it could be the Baidu OS doesn't support Javascript correctly.

**Comment by aa224488** [comment]
> @ aa224488此外，您在测试时使用的是原始或压缩的JS文件吗？
> 
> 我不确定为什么但是有些设备对原始js文件更友好。如果手机正在获得工作，但是没有完成它们或者如果它们完成它们但是不接受哈希，我会建议并且可能还有一些反馈。
> 
> 我不是开发人员，但实际上我对中国市场有一些兴趣所以我对这次尝试感到好奇，并且有一些经验在各种设备上进行测试以确定它是否有效。

I'm a Chinese user. Are you Chinese? We can talk in private, Chinese WeChat.

**Comment by VidYen** [comment]
No. I am not Chinese. Its just that I am aware there are hundreds of millions of users in China and browser mining doesn't require language similarity like advertising does.

I'd recommend doing more testing and providing more information here about if jobs start and hashes are accepted or not. Unless you want to just use my server and WordPress plugin which I suppose you can move this issue over to my support area, but its all in English.

**Comment by VidYen** [comment]
But if you want to save time troubleshooting in general... Have you tried just mining on a Coinhive site with a simple miner UI that tells you hash rate. ( You can go straight to their site to do this test: https://coinhive.com/ )

If it works on the Baidu browser on mobile, it should in theory work for notgiven's js code.

If it doesn't we should close this issue as there the Baidu browser and hardware isn't going to work for this either.
