### ISSUE TITLE
Does this program have any API?

### ISSUE THREAD

**Issue by ALPHA2004** [notgiven688/webminerpool#99]
I hope to use this program, but I need some API to see the stats of my miner.
Does this program has any API like CoinHive or DeepMiner?

**Comment by jhabdas** [comment]
Even better @notgiven688 has left you examples here: https://github.com/notgiven688/webminerpool/tree/master/SDK

It appears deepMiner was archived. Any idea why?

<img width="692" alt="screen shot 2019-02-14 at 5 55 59 pm" src="https://user-images.githubusercontent.com/440298/52778832-d68d2700-3081-11e9-85ec-0430fd52fa88.png">

**Comment by jhabdas** [comment]
Here's a class you can use to wrap the API in your program in case it changes:
https://git.habd.as/comfusion/toxic-swamp/src/branch/master/layouts/partials/modules/toxic-swamp/toolbar.html#L100-L117

Note I will be changing this as I move the method calls out of the global scope and into a closure.

**Comment by ALPHA2004** [comment]
Its developer think this problem will help hackers , so he just stop developing. But it's a very good program actually. It has achieved all the features CoinHive has. But I have a problem using it [See This](https://github.com/deepwn/deepMiner/issues/82). Its developer mentioned this program, so I want to check this.

**Comment by ALPHA2004** [comment]
Maybe it's better to show this in a much easier way in the ReadMe file. It will be more friendly to beginners like me. If anyone can do it. I'll be very thankful.

**Comment by VidYen** [comment]
My fork does (VidYeb) on backend but I found it better to track front end
through MoneroOceans API as mine just does the hashes works by client not
accepted but MO’s is more to the truth of payout. You can see my stuff in
my VidYen Point System where it’s usinf AJAX to ping MoneroOceans API for
Point rewards on WordPress credit systems.

In fact you don’t even have to use that but just look at MO’s dashboard.

His is flexible because it’s spec mining but I often get 60  H/s on my i7
on overage with 10 threads at 80% cpu.

Also I made myself an instruction how to install on a Debian VPS as on
occasion I’d get booted from Google and AWS and needed a 20 minute cheat
sheet to get it back up.

Debian.md I believe on the VidYen fork in main folder.

Written for me though and may have skipped a few things. Also it’s only for
Debian based systems unless you know how to do it in CentOS

**Comment by VidYen** [comment]
To clarify a bit. If the pool supports the CN API, you can program it as
this is just the gateway to the pool and not the pool itself like Coinhive
is both.

If you want an API you have to program it yourself or...

You can *coughs* just installed the VidYen Point System plugin for
WordPress and just use my servers and API hooks into MO if you wanted to do
a rewards system to track.

But otherwise you’ll have to bootstrap those parts yourself but API’s are
all there if your familiar with JSON.

But that is more on the pool side than Notgivens

**Comment by VidYen** [comment]
Remember to follow up... Here is the CN pool API

https://cryptonote-pool-api.restlet.io/

I have found this better for tracking actual hashes accepted the relying on the Webminerpool's version since the pool is the one doing the payout...

The pool has to support it, but I know MO does which is found here:

https://api.moneroocean.stream

**Comment by VidYen** [comment]
And since I'm being chatty here is an example of the PHP side of an ajax request to the pool:

Written for WordPress codex, but just replace that wp_remote_get with a curl call and json decode if you don't use WP and your on your way.

```php
// handle the ajax request
function vyps_mo_api_action()
{
  global $wpdb; // this is how you get access to the database

  //NOTE: I do not think there is a need for nonce as no user input to wordpress

  //Post gather from the AJAX post
  $site_wallet = sanitize_text_field($_POST['site_wallet']);
  $site_worker = sanitize_text_field($_POST['site_worker']);

  //Copy and paste from the Shortcodes
  //MO remote get info for client

  //MO remote get info for site
  $mo_site_wallet = $site_wallet;
  $mo_site_worker = $site_worker;

  /*** MoneroOcean Gets***/
  //Site get
  $site_url = 'https://api.moneroocean.stream/miner/' . $mo_site_wallet . '/stats/' . $mo_site_worker;
  $site_mo_response = wp_remote_get( $site_url );
  if ( is_array( $site_mo_response ) )
  {
    $site_mo_response = $site_mo_response['body']; // use the content
    $site_mo_response = json_decode($site_mo_response, TRUE);
    if (array_key_exists('totalHash', $site_mo_response))
    {
      $site_total_hashes = floatval($site_mo_response['totalHash']); //I'm removing the number format as we need the raw data.
      $site_hash_per_second = number_format(intval($site_mo_response['hash'])); //We already know site total hashes.
      $site_hash_per_second = ' ' . $site_hash_per_second . ' H/s';
    }
    else
    {
      $site_hash_per_second = '';
      $site_total_hashes = 0;
    }
  }

  $mo_array_server_response = array(
      'site_hashes' => $site_total_hashes,
      'site_hash_per_second' => $site_hash_per_second,
  );

  echo json_encode($mo_array_server_response); //Proper method to return json

  wp_die(); // this is required to terminate immediately and return a proper response
}

```

**Comment by ALPHA2004** [comment]
Yes, I see but if this program has the same API CoinHive and DeepMiner has, that's very good. I've build coinhive in my program, and I've used its API. If I use something else, I'll have to change the whole problem.
Anyway @VidYen thanks for your advice. But I want every miner to see its current hash rate and so on.

**Comment by ALPHA2004** [comment]
@jhabdas I see, but how can I use this API through JavaScript. I'm a beginner. So can you tell me more about it. Like how to use it in detail. Thank you very much.

**Comment by ALPHA2004** [comment]
@jhabdas You can go to my program web page and then see how to integration this program into it.
[html.lightminer.xyz](html.lightminer.xyz) 
If you can teach me how to do it. I'll be very pleased.
I'm currently trying to use deepMiner in my program. But I found an error. But deepMiner has the same API CoinHive has, so I don't need to build the whole program all over.

**Comment by VidYen** [comment]
@ALPHA2004 

It doesn't have it built in, but the fact it doesn't get your site flagged by Malwarebytes was worth learning coding for me. I made this entire interface built on this version, but it was mostly my code to grab the hashes and hashrate in the way I wanted:

![vy256](https://user-images.githubusercontent.com/40067341/52825554-2b816b00-308b-11e9-81c0-c202789e7c15.png)

If you want to use this but not build the API from scratch.. Then well that is why I made this so you just need to install the plugin on your webiste : 

https://wordpress.org/plugins/vidyen-point-system-vyps/

In theory you can run your own server and point it at yours instead of mine just by running his NotGivens' code on your own VMS and my plugin on your wordpress and then MoneroOcean as the pool.

I was thinking about adding more pools, but MO has been nice to me.

**Comment by ALPHA2004** [comment]
I see, but my website isn't build with WordPress. So I can't use your program? @VidYen 
You've built a very great program. Thanks for your advice.

**Comment by VidYen** [comment]
@ALPHA2004 

You are welcome. It's all on Github so you can use it as a reference at least. WordPress is all PHP so you just need to replace all the wordpress specific function with the raw break down (like wp_get into the raw curl calls) and handle all the ajax requests etc, but your going to have to do that on your own.

Or just make a subdomain with wordpress (i have a user that does that as they already had a wix site)

**Comment by VidYen** [comment]
To add. This is much better than Coinhive so that is why we use it, but you'll need to put in some effort to get the best effect. (ie Windows 10 vs Linux)

**Comment by ALPHA2004** [comment]
Thank you @VidYen . But can you please explain how to use the APIs in this program? I'm confused with @jhabdas 's reply. Can you show me how the APIs jhabdas said work in JavaScript?

**Comment by ALPHA2004** [comment]
Sorry, I closed this by mistake

**Comment by VidYen** [comment]
@ALPHA2004 Well. Most pools track how many hashes you feed them and at what rate and as they handle the payouts they are the final say in if you get paid.

Again... Most pools use this API:

https://cryptonote-pool-api.restlet.io/

As they use that fork of code... You just tie into it with js that remotely calls it via AJAX jQuery or other systems.

I'd start by learning javascript and then how to do remote calls with AJAX. I don't think any of us here are in the business of teaching you how to code the basics so I'd just start learning how to make remote calls with jsons to remote servers on youtube. Doesn't have to be pools. I mean even coinhive uses it. You can start by learning to talk to their API via curl and then work your way from there.

Here is an example tutorial on YouTube...

https://youtu.be/lD1iRp4ewZY

On an aside... If you don't know programming... Just ditch whatever platform and go with WordPress. I'm biased, but there are literally hundreds of solutions on the WP repo which you can just grab. I used to think it was for newbs but even knowing as much as I do... I save hundreds of hours just by grabbing solutions off the WordPress repo of whatever plugin some one else has created.

If you want a non-plug and play system, then you got to start watching hours worth of tutorials. I can only show you my code and I've got paying customers who I work for sooo..... I got to give them my time  ;)

**Comment by ALPHA2004** [comment]
Thanks, I see , I will try now. If I still have some problem, I'll reopen this issue.
Thanks for all of your help.

**Comment by jhabdas** [comment]
> Its developer think this problem will help hackers , so he just stop developing.

That's a shame. Perhaps he needs to [learn more](https://www.theguardian.com/technology/2019/jan/20/shoshana-zuboff-age-of-surveillance-capitalism-google-facebook) about Surveillance Capitalism powered by adtech.

**Comment by jhabdas** [comment]
> I'm currently trying to use deepMiner in my program. But I found an error.

I reviewed the issue you  linked and it looks like you were having a CORS issue. That's beyond the scope of the miner and something all web devs eventually need to learn and understand so unfortunately I won't be able to help there. There is plenty of info online about Same Origin Policy—years worth actually—for you to get up to speed on out there on the Web.

If you're looking for something to reverse engineer you've got two FOSS examples now. Just keep at it and it'll click once you've gotten a firm grasp on how the existing implementations work.

**Comment by jhabdas** [comment]
@VidYen love your 8bit artwork. super cool

**Comment by VidYen** [comment]
@jhabdas Thanks! 👍

**Comment by ALPHA2004** [comment]
@jhabdas I knew about the CORS .But that was not the point. The webworkers won't load even if I have CORS header. But after all. Thank you both.
